### ISSUE TITLE
Is a F1 population acceptable?

### ISSUE THREAD

**Issue by knagasaka** [baozg/Potato_C88#1]
Hi Bao,

Thank you for sharing your nice codes!
I have a question about s1 population for Haplotype-aware Genetic Mapping.
Is there any reason why you chose S1 population? and can I use F1 population instead of S1 population?

In addition, have you tried scaffolding without HiC data (only using linkage map)?

Thank you in advance!
Kyoka

**Comment by baozg** [comment]
Hi Kyoka,

Thanks for your attention. Since we only want to assemble the 4 haplotypes of C88, we choose the selfing population. It's just a combination of 4 haplotypes. If you use F1 population, I think our solution doesn't work directly. You have to untangle 8 haplotypes together (female and male parent). Maybe you can look at this paper [Haplotype-resolved assembly of a tetraploid potato genome using long reads and low-depth offspring data](https://www.biorxiv.org/content/10.1101/2022.05.10.491293v1).  But you can definitely use `hifiasm-polyploid` after phasing with other methods.

We did try the AllHiC and other HiC scaffolding, but it cannot work well in the potato genomes. HiC scaffolding methods cannot distinguish the collapsed haplotype from other unique haplotigs. If you have a divergence species with enough variants between haplotypes, maybe you can try AllHiC first. 


Best regards
Zhigui

**Comment by knagasaka** [comment]
Hi Zhigui,

Thank you for your reply! I will check the paper you suggested. 
Umm, so it is not a matter of SNP count, but of haplotype count.

The species of my interest is also autotetraploid, so I can follow your method.

Many Thanks,
Kyoka
