### ISSUE TITLE
{input.gz1} {input.gz2} in step3

### ISSUE THREAD

**Issue by ucsfpan** [baozg/Potato_C88#5]
Hi Zhigui,
Thanks for providing this nice workflow. Now I have a longread hifireads for genome assembly and I have finished step1 and step2.
The step3  
  bwa mem -M -R "@RG\tID:${s}\tSM:${s}\tPL:ILLUMINA" -t 8 ref/C88.fa {input.gz1} {input.gz2}| samtools view -@ 8 -Sb - | amtools sort -@ {threads} -o {output.bam} - so what are the  {input.gz1} {input.gz2} files, maybe the short reads related to the same sample?

Also, I am interested in whether this pipeline can be used for cancer cell line with whole genome doubling(tetraploid cell line). Thanks so much.

**Comment by baozg** [comment]
Hi @ucsfpan,

Thanks! The step3 was using the selfing population of the parent (the individual you want to assemble, at least with HiFi and HiC data), and mapping back to the initial assembly. In our case, we have collected 1034 offspring and sequenced them about 1x for phasing.

For the cancer cell line, as I know you cannot get the selfing population. Maybe you need consider strand-seq for phasing with cell line. Sorry I cannot give you more suggestion since I mainly work with plant.

**Comment by ucsfpan** [comment]
Thanks so much. Your advice really helps.
